name: "CodeQL-Dismiss-Alerts-Test"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["java", "javascript", "cpp", "csharp", "go", "ruby"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          packs: codeql/${{ matrix.language }}-queries:AlertSuppression.ql

      - name: Build java
        if: ${{ matrix.language == 'java' }}
        run: |
          tests/java/build

      - name: Build cpp
        if: ${{ matrix.language == 'cpp' }}
        run: |
          cd tests/cpp/
          make add-user

      - name: Build csharp
        if: ${{ matrix.language == 'csharp' }}
        run: |
          cd tests/csharp
          dotnet build

      - name: Perform CodeQL Analysis
        id: analyze
        uses: github/codeql-action/analyze@v2
        with:
          output: ${{ matrix.language }}-sarif-results

      - name: dismiss-alerts
        uses: aibaars/dismiss-alerts@unsuppress
        with:
          sarif-id: ${{ steps.analyze.outputs.sarif-id }}
          sarif-file: ${{ matrix.language }}-sarif-results/${{ matrix.language }}.sarif
        env:
          GITHUB_TOKEN: ${{ github.token }}
